name: Android CI

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean Build
        run: ./gradlew clean

      # 1. feature → develop PR: Lint + UnitTest
      - name: Run Ktlint
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/')
        run: ./gradlew ktlintCheck

      - name: Run Unit Tests for feature PR
        if: github.event_name == 'pull_request' && startsWith(github.head_ref, 'feature/')
        run: ./gradlew testDebugUnitTest

      #2. develop Push: UI Test
      - name: Run UI Test (Instrumented)
        if: github.ref_name == 'develop'
        run: ./gradlew connectedDebugAndroidTest

